name: chunked_uploader
description: An easy-to-use package to upload files in chunks using Dio for mobile, desktop and web.
version: 1.1.0
homepage: https://github.com/Taskulu/chunked_uploader
repository: https://github.com/Taskulu/chunked_uploader

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  dio: ">=4.0.0 <6.0.0"
  universal_io: ^2.2.2
  async: ^2.11.0
